### ISSUE TITLE
5.7: build fails with new glibc

### ISSUE THREAD

**Issue by kloczek** [strace/strace#143]
After just upgrade glibc to latest version I found another issue:
```
[tkloczko@barrel strace-5.7]$ make
make  all-recursive
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/strace-5.7'
Making all in .
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/strace-5.7'
gcc -DHAVE_CONFIG_H   -I./linux/x86_64 -I./linux/x86_64 -I./linux -I./linux -I. -I.      -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings -Werror   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -c -o libstrace_a-io_uring.o `test -f 'io_uring.c' || echo './'`io_uring.c
In file included from ./static_assert.h:11,
                 from xlat/uring_op_flags.h:4,
                 from io_uring.c:14:
io_uring.c:32:1: error: static assertion failed: "struct io_cqring_offsets.resv is missing, please update the decoder"
   32 | static_assert(0, "struct io_cqring_offsets.resv is missing"
      | ^~~~~~~~~~~~~
```

**Comment by ldv-alt** [comment]
Please try to build the latest commit from master branch instead.
This issue must have been fixed by commit fded17c15bca4150165f899cc47f67bab963d9a7.

**Comment by kloczek** [comment]
After adding all patches from master I'm still not able to build strace.
```
[tkloczko@barrel strace-5.7]$ make
make  all-recursive
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/strace-5.7'
Making all in .
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/strace-5.7'
gcc -DHAVE_CONFIG_H   -I./linux/x86_64 -I./linux/x86_64 -I./linux -I./linux -I. -I.      -Wall -Wempty-body -Wformat-security -Wignored-qualifiers -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-parameter-type -Wnested-externs -Wold-style-declaration -Wold-style-definition -Woverride-init -Wsign-compare -Wtype-limits -Wwrite-strings -Werror   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -c -o libstrace_a-access.o `test -f 'access.c' || echo './'`access.c
access.c:12:10: fatal error: xlat/access_modes.h: No such file or directory
   12 | #include "xlat/access_modes.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:4186: libstrace_a-access.o] Error 1
```

**Comment by ldv-alt** [comment]
I bet you haven't invoked ./bootstrap; please read INSTALL-git.md describing how to build strace from git repository.
